pipeline {
    agent any
    stages {
        stage('Build Application') {
            agent{
                label 'Ubuntu-Agent'
            }
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Create Tomcat Docker Image'){
            agent{
                label 'Ubuntu-Agent'
            }
            steps {
                sh "pwd"
                sh "ls -a"
                sh "docker build -f ./java-tomcat-sample-docker/Dockerfile -t tomcatsamplewebapp:${env.BUILD_ID} ./java-tomcat-sample-docker"
            }
        }

    }
}