pipeline {
    agent { label 'Master' }
    stages {
        stage('Build Application') {
            steps {
                bat 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Create Tomcat Docker Image'){
            steps {
                bat "docker build -f ./java-tomcat-sample-docker/Dockerfile -t tomcatsamplewebapp:${env.BUILD_ID} ./java-tomcat-sample-docker"
            }
        }

    }
}
